import requests
import sys
import json
import time
from datetime import datetime

class AISpatialIntelligenceAPITester:
    def __init__(self, base_url="https://modular-visualizer.preview.emergentagent.com"):
        self.base_url = base_url
        self.tests_run = 0
        self.tests_passed = 0
        self.results = []
        self.session_token = None

    def log_result(self, test_name, passed, details=""):
        """Log test result"""
        self.tests_run += 1
        if passed:
            self.tests_passed += 1
            print(f"✅ {test_name}")
        else:
            print(f"❌ {test_name} - {details}")
        
        self.results.append({
            "test": test_name,
            "passed": passed,
            "details": details
        })

    def test_ai_chat_without_auth(self):
        """Test AI chat endpoint returns 401 without authentication"""
        try:
            response = requests.post(
                f"{self.base_url}/api/ai/chat",
                json={"message": "Make it more minimal"},
                timeout=10
            )
            if response.status_code == 401:
                self.log_result("POST /api/ai/chat without auth returns 401", True)
                return True
            else:
                self.log_result("AI chat without auth", False, f"Expected 401, got {response.status_code}")
        except Exception as e:
            self.log_result("AI chat without auth", False, f"Error: {str(e)}")
        return False

    def test_ai_chat_empty_message(self):
        """Test AI chat endpoint returns 400 for empty message"""
        try:
            response = requests.post(
                f"{self.base_url}/api/ai/chat",
                json={"message": ""},
                timeout=10
            )
            if response.status_code == 400:
                self.log_result("POST /api/ai/chat with empty message returns 400", True)
                return True
            else:
                self.log_result("AI chat empty message", False, f"Expected 400, got {response.status_code}")
        except Exception as e:
            self.log_result("AI chat empty message", False, f"Error: {str(e)}")
        return False

    def test_structured_ai_response_format(self):
        """Test that AI responses follow the structured format with sections"""
        # This test would require authentication, so we'll test the parsing logic instead
        # by checking if the frontend can handle structured responses
        
        # Sample structured response that should be generated by the AI
        sample_response = """[INTERPRETATION]
User wants a more minimal design approach for their current configuration.

[MODE]
Design Agent + Style Agent

[REASONING]
Minimal design focuses on essential forms and clean lines. We should reduce visual complexity while maintaining functionality.

[TRANSFORMS]
1. Simplify the desk shape to clean rectangular form
2. Use neutral color palette - Arctic White or Void Black
3. Select Bamboo Composite for natural, minimal aesthetic

[VARIANTS]
MINIMAL: Pure white desk with bamboo, no decorative elements
BOLD: Black desk with sharp edges, carbon fiber accents  
EXPERIMENTAL: Floating desk concept with hidden supports

[ACTION]
```json
{
  "action": "modify",
  "target": "shape",
  "parameters": {
    "shape": "desk",
    "color": "#e8e8e8",
    "colorName": "Arctic White",
    "material": "Bamboo Composite",
    "notes": "Minimal aesthetic with clean lines"
  }
}
```"""
        
        # Test if we can parse this structured format
        try:
            sections = self.parse_ai_response(sample_response)
            required_sections = ['INTERPRETATION', 'MODE', 'REASONING', 'TRANSFORMS', 'VARIANTS', 'ACTION']
            
            missing_sections = [s for s in required_sections if s not in sections]
            if not missing_sections:
                # Test JSON extraction from ACTION section
                action_json = self.extract_action_json(sections['ACTION'])
                if action_json and 'action' in action_json and 'parameters' in action_json:
                    self.log_result("Structured AI response format parsing works correctly", True)
                    return True
                else:
                    self.log_result("Structured AI response", False, "Failed to extract valid JSON from ACTION section")
            else:
                self.log_result("Structured AI response", False, f"Missing sections: {missing_sections}")
        except Exception as e:
            self.log_result("Structured AI response", False, f"Error: {str(e)}")
        return False

    def parse_ai_response(self, text):
        """Parse structured AI response into sections"""
        sections = {}
        markers = ['INTERPRETATION', 'MODE', 'REASONING', 'TRANSFORMS', 'VARIANTS', 'ACTION']
        current = None
        buffer = []

        for line in text.split('\n'):
            trimmed = line.strip()
            matched_marker = None
            for m in markers:
                if trimmed == f'[{m}]' or trimmed.startswith(f'**[{m}]**') or trimmed.startswith(f'[{m}]'):
                    matched_marker = m
                    break
            
            if matched_marker:
                if current:
                    sections[current] = '\n'.join(buffer).strip()
                current = matched_marker
                buffer = []
            else:
                buffer.append(line)
        
        if current:
            sections[current] = '\n'.join(buffer).strip()
        
        return sections

    def extract_action_json(self, action_text):
        """Extract JSON from ACTION section"""
        if not action_text:
            return None
        try:
            json_match = None
            if '```json' in action_text:
                parts = action_text.split('```json')
                if len(parts) > 1:
                    json_part = parts[1].split('```')[0].strip()
                    json_match = json_part
            elif '{' in action_text and '}' in action_text:
                # Find JSON object
                start = action_text.find('{')
                end = action_text.rfind('}') + 1
                json_match = action_text[start:end]
            
            if json_match:
                return json.loads(json_match)
        except:
            pass
        return None

    def test_products_endpoint(self):
        """Test products endpoint returns seeded products"""
        try:
            response = requests.get(f"{self.base_url}/api/products", timeout=10)
            if response.status_code == 200:
                products = response.json()
                if isinstance(products, list) and len(products) >= 6:
                    # Check for expected seeded products
                    product_ids = [p.get('product_id') for p in products]
                    expected_products = ['prod_modular_desk_01', 'prod_aero_chair_01', 'prod_ambient_light_01']
                    found_products = [pid for pid in expected_products if pid in product_ids]
                    
                    if len(found_products) >= 3:
                        self.log_result("GET /api/products returns seeded products (backend alive check)", True)
                        return True
                    else:
                        self.log_result("Products endpoint", False, f"Missing expected products: {set(expected_products) - set(found_products)}")
                else:
                    self.log_result("Products endpoint", False, f"Expected at least 6 products, got {len(products) if isinstance(products, list) else 'invalid'}")
            else:
                self.log_result("Products endpoint", False, f"Status {response.status_code}")
        except Exception as e:
            self.log_result("Products endpoint", False, f"Error: {str(e)}")
        return False

    def run_all_tests(self):
        """Run all AI Co-Designer tests"""
        print("🧠 Testing Aetheris Spatial - AI Co-Designer & Master Agent System")
        print("=" * 70)
        
        # Test basic API functionality
        self.test_products_endpoint()
        self.test_ai_chat_without_auth()
        self.test_ai_chat_empty_message()
        
        # Test new structured response format
        self.test_structured_ai_response_format()
        
        print("\n" + "=" * 70)
        print(f"📊 AI Co-Designer Tests: {self.tests_passed}/{self.tests_run} passed")
        
        return self.tests_passed, self.tests_run, self.results

def main():
    tester = AISpatialIntelligenceAPITester()
    passed, total, results = tester.run_all_tests()
    
    if passed == total:
        print("🎉 All AI Co-Designer tests passed!")
        return 0
    else:
        print(f"⚠️  {total - passed} tests failed")
        return 1

if __name__ == "__main__":
    sys.exit(main())